version: '3'

services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'yarn run start:dev --debug 0.0.0.0:${APP_DEBUG_PORT}'
    ports:
      - '${APP_OUT_PORT}:${APP_PORT}'
      - '${APP_DEBUG_OUT_PORT}:${APP_DEBUG_PORT}'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0-alpine3.14
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - '${DB_OUT_PORT}:${DB_PORT}'

volumes:
  db-data: